# Generated by Django 5.2.1 on 2025-05-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_quantiy',
            new_name='stock_quantity',
        ),
    ]
