# Generated by Django 5.2.1 on 2025-05-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_stock_quantiy_product_stock_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='featured_image',
        ),
    ]
