# Generated by Django 5.2.1 on 2025-06-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer')], default='admin', max_length=20),
        ),
    ]
