# Generated by Django 5.2.1 on 2025-06-05 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordeitem'),
        ('store', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdeItem',
            new_name='OrderItem',
        ),
    ]
